//%attributes = {"invisible":true}
C_VARIANT(atExcludedTables)
C_VARIANT(Connection_ID_fk)
C_VARIANT(Connection_ID_l)
C_VARIANT(End_Time_ms_l)
C_LONGINT(Error_l)
C_TEXT(Error_Method_t)
C_COLLECTION(Error_Stack_cln)
C_TEXT(Filter_Value_t)
C_VARIANT(Get_Excluded_Tables)
C_VARIANT(progBar_Close)
C_LONGINT(Queries)
C_TEXT(queryExtraInfo_t)
C_VARIANT(SQL_Tables_at)
C_VARIANT(Start_Time_ms_l)